permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ['Rakefile', 'README.md', 'write_list.md', 'License.md']
markdown: rdiscount

domain: jhchabran.com
title: JHChabran
subtitle: Thoughts on Ruby, CoffeeScript and Vim from a passionate developer.

author: jhchabran
email: jh@chabran.fr

url: http://jhchabran.com
google_analytics: UA-36508562-1
disqus:
  id: jhchabran
